### ISSUE TITLE
Duplicate IP Address

### ISSUE THREAD

**Issue by ChandraOrbit** [SecOps-Institute/FacebookIPLists#1]
This already exist

69.63.176.0/20
69.63.176.0/21
69.63.184.0/21
66.220.144.0/20
69.63.176.0/20

**Comment by aarvee11** [comment]
Hey @ChandraOrbit Thank you for the report and apologies for the late response. The IP Addresses listing is based on the RADB listing and hence did not want to fiddle around the IP networks by subnetting or supernetting them!
